# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - uses: actions/setup-node@v4
        with:
          node-version: 18
        name: Set up Node.js

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start backend services
        run: |
          git clone https://github.com/PureMVC/puremvc-js-demo-microservice-employeeadmin
          cd puremvc-js-demo-microservice-employeeadmin
          docker compose up -d
          cd ..

      - name: Wait for backend services to be ready
        run: sleep 30

      - name: Start Vite server
        run: |
          nohup npm run build & npm run preview &
          sleep 5 # Gives Vite some time to start up

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
